#!/usr/bin/env python3
# fetch_and_classify.py
# Requires: feedparser, requests, beautifulsoup4

import feedparser
import requests
from bs4 import BeautifulSoup
import csv
import json
import hashlib
import os
import datetime

# ========== CONFIG ==========
OUT_CSV = "tools_db.csv"
OUT_JSON = "tools_db.json"
OUT_HTML = "index.html"
SOURCES = [
    "https://www.producthunt.com/feed",
    "https://news.ycombinator.com/rss",
    "https://www.reddit.com/r/ProductHunt/.rss",
    "https://www.reddit.com/r/MachineLearning/.rss",
    "https://www.reddit.com/r/artificial/.rss",
]

CATEGORIES = {
    "Generative AI": ["generative", "gpt", "llm", "text-to-image", "stable diffusion", "dall", "gpt-", "chatgpt"],
    "Model / ML Framework": ["model", "framework", "pytorch", "tensorflow", "transformer", "huggingface"],
    "Developer Tool": ["cli", "sdk", "api", "dev", "plugin", "extension", "integration", "tooling"],
    "Productivity App": ["productivity", "task", "notes", "todo", "calendar", "work", "collaborat", "docs"],
    "Data / Analytics": ["analytics", "etl", "data", "pipeline", "dashboard", "visualiz"],
    "Design / UI": ["design", "ux", "mockup", "figma", "prototype", "illustrat", "ui kit"],
    "Security / Privacy": ["security", "privacy", "compliance", "encrypt"],
    "Other": []
}

FIELDS = ["id", "title", "description", "link", "published", "source", "categories", "first_seen_iso"]

def canonical_id(text):
    import hashlib
    return hashlib.sha1(text.encode('utf-8')).hexdigest()

def text_score_categories(text):
    t = text.lower()
    hits = []
    for cat, kwlist in CATEGORIES.items():
        for kw in kwlist:
            if kw in t:
                hits.append(cat)
                break
    if not hits:
        hits = ["Other"]
    return hits

def fetch_rss(url):
    d = feedparser.parse(url)
    items = []
    for e in d.entries:
        title = e.get("title", "").strip()
        desc = e.get("summary", "") or e.get("description", "")
        link = e.get("link", "")
        published = e.get("published", "") or e.get("updated", "")
        items.append({"title": title, "description": BeautifulSoup(desc, "html.parser").get_text(), "link": link, "published": published, "source": url})
    return items

def fetch_html_title_description(url):
    try:
        r = requests.get(url, timeout=8, headers={"User-Agent":"Mozilla/5.0 (compatible)"})
        soup = BeautifulSoup(r.text, "html.parser")
        t = (soup.title.string if soup.title else "") or ""
        p = soup.find("meta", {"name":"description"}) or soup.find("meta", {"property":"og:description"})
        desc = p["content"] if p and p.get("content") else ""
        return t.strip(), desc.strip()
    except Exception:
        return "", ""

def load_existing():
    items = {}
    if os.path.exists(OUT_CSV):
        import csv
        with open(OUT_CSV, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                items[row["id"]] = row
    return items

def save_all(all_items):
    import json, csv
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        for it in all_items:
            writer.writerow({k: it.get(k, "") for k in FIELDS})
    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(all_items, f, ensure_ascii=False, indent=2)

def generate_index_html():
    html = """<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>ai-tool-scanner — Daily Trend Dashboard</title>
  </head>
  <body>
    <div id="root">
      <p>This site is generated by the ai-tool-scanner project. Build the frontend or use the prebuilt static bundle in /dist.</p>
    </div>
  </body>
</html>
"""
    with open(OUT_HTML, "w", encoding="utf-8") as f:
        f.write(html)

def main():
    existing = load_existing()
    new_items = []
    now_iso = datetime.datetime.utcnow().isoformat() + "Z"
    for src in SOURCES:
        try:
            items = fetch_rss(src)
        except Exception:
            items = []
        for it in items:
            title = it.get("title","") or ""
            link = it.get("link","") or ""
            keytext = (title + " " + link).strip()
            if not keytext:
                continue
            cid = canonical_id(keytext)
            if cid in existing:
                continue
            if not it.get("description"):
                t,d = fetch_html_title_description(link)
                if not title and t:
                    title = t
                if d:
                    it["description"] = d
            cats = text_score_categories((title + " " + it.get("description","")).lower())
            record = {"id": cid, "title": title, "description": it.get("description",""), "link": link, "published": it.get("published",""), "source": src, "categories": ";".join(cats), "first_seen_iso": now_iso}
            existing[cid] = record
            new_items.append(record)
    all_items = list(existing.values())
    save_all(all_items)
    generate_index_html()
    print(f"Found {len(new_items)} new items. Total stored: {len(all_items)}")

if __name__ == "__main__":
    main()
